### ISSUE TITLE
Analytics Platform Research

### ISSUE THREAD

**Issue by danwritecode** [aiku-ai/AiKu#25]
We need to do some baseline research on how we are going to do analytics.

To get started, this video is an excellent: https://youtu.be/bVRo68NByvE

**Comment by adragione** [comment]
Looking into Matomo server-side tracking options so we can get around front-end ad-blockers affecting client-side traffic getting to our Matomo server. Still reviewing other alternatives as mentioned in the YouTube video above. We'll likely need to handle a short-term plan (to get immediate metrics for initial launch) and a long-term plan to capture metrics over long periods of time.

**Comment by adragione** [comment]
Research complete and implementation pattern has been chosen. Work to implement analytics will be tracked through this issue:

https://github.com/aiku-ai/AiKu/issues/38
