### ISSUE TITLE
Automatic tweeting of popular AiKus

### ISSUE THREAD

**Issue by danwritecode** [aiku-ai/AiKu#28]

**Comment by adragione** [comment]
We'll need to think about how to track popularity of AiKus. V1 can work off of the number of likes, but eventually it can include metrics around number of times shared or exported/saved.

**Comment by adragione** [comment]
Tweet structure:

 - Link to AiKu
 - Author's Username
 - Author's profile URL
 - Number of likes
 - Number of shares

**Comment by adragione** [comment]
We also need to create an AiKu Twitter account so we can register with their API. Working with @danwritecode on that this morning.

**Comment by adragione** [comment]
new handle created: @aiku_app

**Comment by danwritecode** [comment]
with the deprecation of the twitter API, it's uncertain if we will do this.
