### ISSUE TITLE
New endpoints for popular AiKus

### ISSUE THREAD

**Issue by adragione** [aiku-ai/AiKu#39]
We need to create an additional endpoint that can be called from the backend which will return the most popular AiKus (based on our stated popularity metrics with their associated weights) and will accept a parameter for number of AiKus to return, sorted in order of popularity descending.

This has a dependency on this feature:
https://github.com/danwritecode/AiKu/issues/38

**Comment by danwritecode** [comment]
Closing for now as whether or not we develop the tweeting feature is in the air.
